// Role - action + reducer keep in sync

export const SIGN_IN_ACCOUNT = "SIGN_IN_ACCOUNT";
export const SIGN_IN_ACCOUNT_SUCCESS = "SIGN_IN_ACCOUNT_SUCCESS";
export const SIGN_IN_ACCOUNT_ERROR = "SIGN_IN_ACCOUNT_ERROR";

export const LOGOUT_FROM_ACCOUNT = "LOGOUT_FROM_ACCOUNT";
export const USER_AUTH_CHECK = "USER_AUTH_CHECK";

export const SIGN_UP_ACCOUNT = "SIGN_UP_ACCOUNT";
export const SIGN_UP_ACCOUNT_SUCCESS = "SIGN_UP_ACCOUNT_SUCCESS";
export const SIGN_UP_ACCOUNT_ERROR = "SIGN_UP_ACCOUNT_ERROR";

export const SET_MOVIE_ID_FROM_VIEW_PORT = "SET_MOVIE_ID_FROM_VIEW_PORT";

export const SET_SORTBY_VALUE = "SET_SORTBY_VALUE";
